spring:



  messages:
    basename: messages/ValidationMessages,messages/i18n/messages
    encoding: UTF-8

  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_db
    username: goorm-board
    password: goorm1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   # ??? ???? ??? ??/????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  devtools:
    restart:
      enabled: true        # ??? ?? ???
      exclude: static/**   # static ??? ??? ???? ??
    livereload:
      enabled: true        # LiveReload ?? ??? (?? ??: 35729)
    thymeleaf:
      cache: false          # ??? ?? ???? (?? ??? ?? F5? ??)

      logging:
        level:
          org.thymeleaf: DEBUG
          web: DEBUG


